export const ShopActionTypes = {
  FATCH_COLLECTIONS_START: 'FATCH_COLLECTIONS_START',
  FATCH_COLLECTIONS_SUCCESS: 'FATCH_COLLECTIONS_SUCCESS',
  FATCH_COLLECTIONS_FAILURE: 'FATCH_COLLECTIONS_FAILURE',
}
